In [6]:
!pip install geopy

Collecting geopy
  Downloading geopy-2.0.0-py3-none-any.whl (111 kB)
     |████████████████████████████████| 111 kB 3.8 MB/s eta 0:00:01
Collecting geographiclib<2,>=1.49
  Downloading geographiclib-1.50-py3-none-any.whl (38 kB)
Installing collected packages: geographiclib, geopy
Successfully installed geographiclib-1.50 geopy-2.0.0

In [7]:
import pandas as pd
from math import sin,cos, sqrt, atan2
import geopy.distance

In [33]:
df = pd.read_csv('state_att.csv')
df.head()

,Name,State,County,Longitude (N/S),Latitude (E/W),Label,Source,Notes
0,Farmington River Trail,Connecticut,Hartford,41.731227,72.863284,Trail,https://www.tripadvisor.com/Attractions-g28928...,I decided to omit #5 Merritt Parkway (because ...
1,Mystic Seaport Museum,Connecticut,New London,41.361600,71.964600,Museum,NaN,NaN
2,Yale University,Connecticut,New Haven,41.316300,72.922300,University,NaN,NaN
3,The Mark Twain House & Museum,Connecticut,Hartford,41.767000,72.701400,Museum,NaN,NaN
4,Mashantucket Pequot Museum & Research Center,Connecticut,New London,41.466200,71.962700,Museum,NaN,NaN

In [18]:
def cal(lat,lon):
    coords_des = (lat, lon)
    coords_ny = (40.71427, -74.00597)
    return geopy.distance.distance(coords_des, coords_ny).miles

In [34]:
df['distance'] = list(map(cal,df['Longitude (N/S)'],-df['Latitude (E/W)']))

In [35]:
df.head()

,Name,State,County,Longitude (N/S),Latitude (E/W),Label,Source,Notes,distance
0,Farmington River Trail,Connecticut,Hartford,41.731227,72.863284,Trail,https://www.tripadvisor.com/Attractions-g28928...,I decided to omit #5 Merritt Parkway (because ...,92.029012
1,Mystic Seaport Museum,Connecticut,New London,41.361600,71.964600,Museum,NaN,NaN,115.632236
2,Yale University,Connecticut,New Haven,41.316300,72.922300,University,NaN,NaN,70.241414
3,The Mark Twain House & Museum,Connecticut,Hartford,41.767000,72.701400,Museum,NaN,NaN,99.472448
4,Mashantucket Pequot Museum & Research Center,Connecticut,New London,41.466200,71.962700,Museum,NaN,NaN,118.620484

In [36]:
df.to_csv('Project 2 State Attractions.csv',index=False,encoding='utf-8-sig')