In [1]:
import pandas as pd
from datetime import timedelta

In [12]:
# get the github raw data link
u1 = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/'
u2 = '-2020.csv'
# update the date for dataset collection
date = '09-24'
url = u1 + date + u2
df = pd.read_csv(url)
df.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incidence_Rate,Case-Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2020-09-25 04:23:00,33.93911,67.709953,39170,1451,32619,5100.0,Afghanistan,100.620779,3.704366
1,NaN,NaN,NaN,Albania,2020-09-25 04:23:00,41.15330,20.168300,12921,370,7239,5312.0,Albania,448.988811,2.863555
2,NaN,NaN,NaN,Algeria,2020-09-25 04:23:00,28.03390,1.659600,50579,1703,35544,13332.0,Algeria,115.342752,3.367010
3,NaN,NaN,NaN,Andorra,2020-09-25 04:23:00,42.50630,1.521800,1753,53,1203,497.0,Andorra,2268.815117,3.023388
4,NaN,NaN,NaN,Angola,2020-09-25 04:23:00,-11.20270,17.873900,4475,162,1503,2810.0,Angola,13.615784,3.620112

In [13]:
# filter out targeted states
states = ['New York','New Jersey','Massachusetts','Virginia','Maryland','Pennsylvania','Connecticut','Delaware','Rhode Island','Washington DC','West Virginia']
foo = pd.DataFrame(df[df['Province_State'].isin(states)],columns=df.columns).reset_index()
# clean the Last_Update column into date
foo['Last_Update'] = foo['Last_Update'].apply(lambda x: pd.to_datetime(x).date()) - timedelta(days=1)
foo

,index,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incidence_Rate,Case-Fatality_Ratio
0,945,9001.0,Fairfield,Connecticut,US,2020-09-24,41.268099,-73.388117,19985,1421,0,18564.0,"Fairfield, Connecticut, US",2118.554231,7.110333
1,946,9003.0,Hartford,Connecticut,US,2020-09-24,41.802830,-72.731039,14506,1434,0,13072.0,"Hartford, Connecticut, US",1626.743821,9.885565
2,947,9005.0,Litchfield,Connecticut,US,2020-09-24,41.793753,-73.245148,1856,141,0,1715.0,"Litchfield, Connecticut, US",1029.207078,7.596983
3,948,9007.0,Middlesex,Connecticut,US,2020-09-24,41.459497,-72.537149,1564,193,0,1371.0,"Middlesex, Connecticut, US",962.840750,12.340153
4,949,9009.0,New Haven,Connecticut,US,2020-09-24,41.408033,-72.936204,14319,1115,0,13204.0,"New Haven, Connecticut, US",1675.212955,7.786857
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340,3704,51830.0,Williamsburg,Virginia,US,2020-09-24,37.281313,-76.709051,178,7,0,171.0,"Williamsburg, Virginia, US",1190.316972,3.932584
341,3705,51840.0,Winchester,Virginia,US,2020-09-24,39.170545,-78.173251,494,4,0,490.0,"Winchester, Virginia, US",1759.384572,0.809717
342,3706,51195.0,Wise,Virginia,US,2020-09-24,36.974615,-82.624105,398,9,0,389.0,"Wise, Virginia, US",1064.655057,2.261307
343,3707,51197.0,Wythe,Virginia,US,2020-09-24,36.915820,-81.078341,229,4,0,225.0,"Wythe, Virginia, US",798.354483,1.746725
344,3708,51199.0,York,Virginia,US,2020-09-24,37.243748,-76.544128,541,8,0,533.0,"York, Virginia, US",792.325718,1.478743

In [14]:
foo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345 entries, 0 to 344
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   index                345 non-null    int64
 1   FIPS                 344 non-null    float64
 2   Admin2               345 non-null    object
 3   Province_State       345 non-null    object
 4   Country_Region       345 non-null    object
 5   Last_Update          345 non-null    object
 6   Lat                  336 non-null    float64
 7   Long_                336 non-null    float64
 8   Confirmed            345 non-null    int64
 9   Deaths               345 non-null    int64
 10  Recovered            345 non-null    int64
 11  Active               345 non-null    float64
 12  Combined_Key         345 non-null    object
 13  Incidence_Rate       336 non-null    float64
 14  Case-Fatality_Ratio  341 non-null    float64
dtypes: float64(6), int64(4), object(5)
memory usage: 40.6+ KB

In [15]:
# combine the files
# out = pd.DataFrame() ##### !!!quote it after your first run!
out = pd.concat([out,foo])

In [16]:
out

,index,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incidence_Rate,Case-Fatality_Ratio
0,945,9001.0,Fairfield,Connecticut,US,2020-09-23,41.268099,-73.388117,19949,1421,0,18528.0,"Fairfield, Connecticut, US",2114.737971,7.123164
1,946,9003.0,Hartford,Connecticut,US,2020-09-23,41.802830,-72.731039,14456,1434,0,13022.0,"Hartford, Connecticut, US",1621.136680,9.919757
2,947,9005.0,Litchfield,Connecticut,US,2020-09-23,41.793753,-73.245148,1849,140,0,1709.0,"Litchfield, Connecticut, US",1025.325370,7.571660
3,948,9007.0,Middlesex,Connecticut,US,2020-09-23,41.459497,-72.537149,1560,193,0,1367.0,"Middlesex, Connecticut, US",960.378241,12.371795
4,949,9009.0,New Haven,Connecticut,US,2020-09-23,41.408033,-72.936204,14294,1114,0,13180.0,"New Haven, Connecticut, US",1672.288147,7.793480
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340,3704,51830.0,Williamsburg,Virginia,US,2020-09-24,37.281313,-76.709051,178,7,0,171.0,"Williamsburg, Virginia, US",1190.316972,3.932584
341,3705,51840.0,Winchester,Virginia,US,2020-09-24,39.170545,-78.173251,494,4,0,490.0,"Winchester, Virginia, US",1759.384572,0.809717
342,3706,51195.0,Wise,Virginia,US,2020-09-24,36.974615,-82.624105,398,9,0,389.0,"Wise, Virginia, US",1064.655057,2.261307
343,3707,51197.0,Wythe,Virginia,US,2020-09-24,36.915820,-81.078341,229,4,0,225.0,"Wythe, Virginia, US",798.354483,1.746725
344,3708,51199.0,York,Virginia,US,2020-09-24,37.243748,-76.544128,541,8,0,533.0,"York, Virginia, US",792.325718,1.478743

In [ ]:
# when you're done, export to csv
out.to_csv('startdate_enddate.csv',index=False,encoding='utf-8-sig')